---
development:
  cloud_name: petia182
  api_key: '334874723591289'
  api_secret: Lfc7snN0IxFq5wBGZAk2RZJClLc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: petia182
  api_key: '334874723591289'
  api_secret: Lfc7snN0IxFq5wBGZAk2RZJClLc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: petia182
  api_key: '334874723591289'
  api_secret: Lfc7snN0IxFq5wBGZAk2RZJClLc
  enhance_image_tag: true
  static_image_support: false
